Repository Project-Pandora-Game/pandora, pull requests merged in 2023-09, with the labels that each got.

#396 [DEV] Auto-approve for PRs from lead devs or Renovate
  .github/workflows/pr.yml
Labels: Type: Feature, Component: Tooling

#400 [DEV] Fix race condition in automation task
  .github/workflows/pr.yml
Labels: Component: Tooling, Type: Fix

#404 [DEV] Fix: Use PR author for checking
  .github/workflows/pr.yml
Labels: Component: Tooling, Type: Fix

#402 [FEATURE] Character rotation and manual Y offset
  pandora-client-web/src/character/character.ts
  pandora-client-web/src/character/player.ts
  pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
  pandora-client-web/src/components/chatroom/contextMenus/deviceContextMenu.tsx
  pandora-client-web/src/components/wardrobe/itemDetail/wardrobeItemRoomDevice.tsx
  pandora-client-web/src/components/wardrobe/views/wardrobeBodySizeView.tsx
  pandora-client-web/src/components/wardrobe/views/wardrobeExpressionsView.tsx
  pandora-client-web/src/components/wardrobe/views/wardrobeOutfitsView.tsx
  pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
  pandora-client-web/src/components/wardrobe/wardrobe.tsx
  pandora-client-web/src/components/wardrobe/wardrobeBody.tsx
  pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
  pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
  pandora-client-web/src/components/wardrobe/wardrobeTypes.ts
  pandora-client-web/src/editor/graphics/character/appearanceEditor.ts
  pandora-client-web/src/graphics/graphicsCharacter.tsx
  pandora-client-web/test/character/character.test.ts
  pandora-client-web/test/character/player.test.ts
  pandora-common/src/character/index.ts
  pandora-common/src/event.ts
  pandora-common/src/networking/client_shard.ts
  pandora-common/src/networking/shard_client.ts
  pandora-server-directory/src/database/dbHelper.ts
  pandora-server-shard/src/character/character.ts
  pandora-server-shard/src/room/room.ts
Labels: Type: Feature, Component: Graphics, Component: Asset framework

#406 [DEV] Improve webpack watch detection, show progress
  .vscode/tasks.json
  pandora-client-web/package.json
  pandora-client-web/webpack.config.ts
Labels: Type: Improvement, Component: Tooling

#407 [FIX] Fix character back view being broken
  pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
Labels: Component: Graphics, Type: Fix, Priority: High

#408 [FEATURE] character menu from device menu
  pandora-client-web/src/components/chatroom/contextMenus/characterContextMenu.tsx
  pandora-client-web/src/components/chatroom/contextMenus/deviceContextMenu.tsx
Labels: Type: Improvement, Component: Client

#409 [FIX] Fix culling beak broken on characters with filters applied
  pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
Labels: Component: Graphics, Type: Fix

#410 [FEATURE] require room device leave before room leave
  pandora-client-web/src/components/header/leaveButton.tsx
  pandora-common/src/networking/client_directory.ts
  pandora-common/src/networking/directory_shard.ts
  pandora-server-directory/src/account/character.ts
  pandora-server-shard/src/networking/socketio_directory_connector.ts
Labels: Type: Feature, Component: Client, Component: Core

#414 [DEV] Enable Renovate automerge for non-major updates
  .github/renovate.json
  .github/workflows/ci.yml
Labels: Type: Improvement, Component: Tooling

#415 [DEV] Fix autoapprove job failing if run multiple times
  .github/workflows/automation-autoapprove.yml
  .github/workflows/pr-lint.yml
Labels: Component: Tooling, Type: Fix

#416 [FIX] Hotfix: An important line got lost somewhere
  .github/workflows/automation-autoapprove.yml
Labels: Component: Tooling, Type: Fix

#412 [CHANGE] Rework pose enforcement into requested and actual poses
  pandora-client-web/src/assets/appearanceValidation.ts
  pandora-client-web/src/character/character.ts
  pandora-client-web/src/common/useDebounceValue.ts
  pandora-client-web/src/common/useRemotelyUpdatedUserInput.ts
  pandora-client-web/src/components/chatroom/chatRoomCharacter.tsx
  pandora-client-web/src/components/chatroom/chatRoomDevice.tsx
  pandora-client-web/src/components/chatroom/commands.ts
  pandora-client-web/src/components/chatroomAdmin/chatroomAdmin.scss
  pandora-client-web/src/components/chatroomAdmin/chatroomAdmin.tsx
  pandora-client-web/src/components/common/selectionIndicator/selectionIndicator.scss
  pandora-client-web/src/components/common/selectionIndicator/selectionIndicator.tsx
  pandora-client-web/src/components/wardrobe/views/wardrobeBodySizeView.tsx
  pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
  pandora-client-web/src/components/wardrobe/wardrobe.scss
  pandora-client-web/src/components/wardrobe/wardrobeGraphics.tsx
  pandora-client-web/src/editor/components/bones/bones.tsx
  pandora-client-web/src/editor/graphics/character/appearanceEditor.ts
  pandora-client-web/src/graphics/appearanceConditionEvaluator.ts
  pandora-client-web/src/graphics/graphicsCharacter.tsx
  pandora-client-web/src/styles/_forms.scss
  pandora-common/src/assets/appearance.ts
  pandora-common/src/assets/appearanceActions.ts
  pandora-common/src/assets/appearanceLimit.ts
  pandora-common/src/assets/appearanceValidation.ts
  pandora-common/src/assets/definitions.ts
  pandora-common/src/assets/manipulators/globalStateManipulator.ts
  pandora-common/src/assets/state/characterState.ts
  pandora-common/src/character/restrictionsManager.ts
  pandora-common/src/networking/shard_directory.ts
  pandora-server-directory/src/networking/manager_shard.ts
  pandora-server-shard/src/database/directoryDb.ts
Labels: Type: Improvement, Component: Asset framework

#417 [FIX] Preserve chat input mode when switching screens
  pandora-client-web/src/components/chatroom/chatInput.tsx
  pandora-client-web/src/components/chatroom/chatroom.tsx
  pandora-client-web/src/components/gameContext/gameContextProvider.tsx
  pandora-client-web/src/components/wardrobe/views/wardrobePoseView.tsx
  pandora-client-web/src/components/wiki/pages/intro.tsx
Labels: Component: Client, Type: Fix
