Repository Project-Pandora-Game/pandora, pull requests merged in 2024-06, with the labels that each got.

#772 [FEATURE] show lock password
  pandora-client-web/src/assets/appearanceValidation.ts
  pandora-client-web/src/components/wardrobe/modules/wardrobeModuleLockSlot.tsx
  pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
  pandora-client-web/src/components/wardrobe/wardrobeContext.tsx
  pandora-client-web/src/editor/components/wardrobe/wardrobe.tsx
  pandora-common/src/assets/appearanceActionProblems.ts
  pandora-common/src/assets/appearanceActionProcessingContext.ts
  pandora-common/src/assets/appearanceActions.ts
  pandora-common/src/assets/appearanceHelpers.ts
  pandora-common/src/assets/item/_internal.ts
  pandora-common/src/assets/item/lock.ts
  pandora-common/src/assets/modules.ts
  pandora-common/src/assets/modules/common.ts
  pandora-common/src/assets/modules/lockSlot.ts
  pandora-common/src/assets/state/globalState.ts
  pandora-common/src/networking/client_shard.ts
  pandora-server-shard/src/networking/manager_client.ts
Labels: Component: Client, Component: Asset framework

#778 [CHORE] Drop unnecessary dependencies overrides
  package.json
  pnpm-lock.yaml
Labels: Type: Improvement, Component: Tooling

#781 [DEV] Bunch of development tooling improvements
  .hooks/coverage-collect.cjs
  .vscode/settings.json
  pandora-client-web/.env.template
  pandora-client-web/package.json
  pandora-client-web/src/components/wardrobe/wardrobeComponents.tsx
  pandora-client-web/src/config/definition.ts
  pandora-client-web/src/networking/socketio_directory_connector.ts
  pandora-client-web/src/networking/socketio_shard_connector.ts
  pandora-client-web/webpack.config.ts
  pandora-server-directory/src/lifecycle.ts
  pandora-server-shard/.env.template
  pandora-server-shard/src/lifecycle.ts
  pandora-tests/package.json
  pandora-tests/playwright.config.ts
  pandora-tests/test/_setup/config.ts
  pandora-tests/test/_setup/global_setup.ts
  pandora-tests/test/utils/helpers.ts
  pandora-tests/test/utils/server.ts
  pnpm-lock.yaml
Labels: Type: Improvement, Component: Tooling

#787 [FIX] Allow scrolling in the remaining Contacts tabs
  pandora-client-web/src/components/accountContacts/accountContacts.tsx
  pandora-client-web/src/components/directMessages/directMessages.scss
  pandora-client-web/src/components/directMessages/directMessages.tsx
Labels: Component: Client, Type: Fix

#788 [DEV] Add PR template
  .github/pull_request_template.md
Labels: Type: Documentation, Type: Feature
